# Railway 项目配置
# 使用 Nixpacks 自动识别 Python 并安装 requirements.txt
[build]
builder = "nixpacks"

# 部署与服务配置
[[services]]
name = "okx-macd-bot"
start = "python -u main.py"
restartPolicy = "always"

# 默认环境变量（可被 Railway Variables 面板覆盖）
# 机密不要写在这里：OKX_API_KEY/OKX_SECRET_KEY/OKX_PASSPHRASE 请在 Railway Variables 设置
[services.env]
SCAN_INTERVAL = "45"
OKX_API_MIN_INTERVAL = "1.8"
SYMBOL_LOOP_DELAY = "0.5"
MAX_RETRIES = "2"
BACKOFF_BASE = "1.0"
BACKOFF_MAX = "4.0"
TP_SL_REFRESH_INTERVAL = "300"